on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check Engine
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - cfg: client
            target: wasm32-unknown-unknown
          - cfg: engine
            target: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target.target }}
      - run: cargo check --target ${{ matrix.target.target }}
        env:
          RUSTFLAGS: --cfg ${{ matrix.target.cfg }}

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - cfg: client
            target: wasm32-unknown-unknown
          - cfg: engine
            target: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target.target }}
          components: clippy
      - run: cargo clippy --target ${{ matrix.target.target }} -- -D warnings
        env:
          RUSTFLAGS: --cfg ${{ matrix.target.cfg }}